const daysData = [
  "Prisimink, gyvenimas kaip kalendorius, po vieną dieną, kol baigsis.",
  "Jei manai, kad tavo diena buvo bloga, prisimink, yra žmonių, kurie alergiški šokoladui.",
  "Patarimas: Niekada nežaisk slėpynių su depresija; ji visada tave suras.",
  "Kodėl jaudintis dėl senėjimo? Bent jau tai geriau nei alternatyva.",
  "Jei jautiesi bevertis, prisimink, kad nulūžęs pieštukas taip pat beprasmis.",
  "Gyvenimo hack'as: Gali sutaupyti daug laiko, jei prie nieko nesiriši.",
  "Ar kada nors pagalvojai, kad kiekvienas tavo įkvėpimas yra vienu mažiau likusiu?",
  "Smagus faktas: Vienintelis dalykas, kurį garantuotai gausi iš gyvenimo, yra mokesčiai ir mirtis.",
  "Jei jautiesi prislėgtas, prisimink, kad gravitacija visada tave prispaudžia prie žemės.",
  "Geros naujienos, tavo gyvenimas nėra filmas; nėra garantijos, kad jis turės laimingą pabaigą.",
  "Būk dėkingas už blogas dienas, jos padaro geras dienas rečiau pasitaikančias.",
  "Prokrastinacija kaip kreditinė kortelė; labai smagu, kol gauni sąskaitą.",
  "Penktadienis 13-oji? Tiesiog dar viena diena dideliame dalykų plane.",
  "Meilė? Puiku, kol prisimeni, kad širdies skausmas jau už kampo.",
  "Nesijaudink dėl prarandamų plaukų; tu įgyji išminties... arba plikimą.",
  "Kodėl jaudintis dėl blogos dienos, kai visada yra rytoj, kad galėtum viską sugadinti?",
  "Sveikinimai, išgyvenai dar vieną dieną egzistencinėje krizėje, vadinamoje gyvenimu.",
  "Prisimink, vienintelis dalykas, garantuotas gyvenime, yra netikrumas.",
  "Dietos patarimas: Gali numesti svorio pamiršęs valgyti... arba dėl streso.",
  "Jei gyvenimas tau duoda citrinų, pasigamink limonadą, tada suvok, kad cukraus neturi.",
  "Geriausia dalis apie pasiekimą dugno – nėra kur eiti, tik į šoną.",
  "Žinai, kad esi suaugęs, kai 'linksmybė' tampa 'atsakomybe' su kauke.",
  "Kiekviena diena artina prie pabaigos, bet argi tai ne jaudina?",
  "Linksmų Kalėdų! Prisimink, Kalėdų senelio elfai yra tik nepakankamai apmokami darbininkai žaislų prakaito fabrike.",
];

export default daysData;
